FREEBSD_KERNCONF=${FREEBSD_KERNCONF:-RK3588-T6-NORE}

UBOOT_BRANCH=${UBOOT_BRANCH:-yuri/rk3588}
UBOOT_DEFCONFIG=${UBOOT_DEFCONFIG:-g98-rk3588_defconfig}
UBOOT_LOGO_CONFIG=${UBOOT_LOGO_CONFIG:-RK3588_FREEBSD_SHOW_LOGO}
UBOOT_BINARY_MARKER=${UBOOT_BINARY_MARKER:-G98-RK3588-${UBOOT_VERSION}}
UBOOT_LOGO_BMP=${UBOOT_LOGO_BMP:-${BOARD_DIR}/assets/logo.bmp}
UBOOT_SOURCE_FILES_DIR=${UBOOT_SOURCE_FILES_DIR:-${BOARD_DIR}/u-boot/files}
UBOOT_FIRMWARE_LAYOUT=${UBOOT_FIRMWARE_LAYOUT:-spi}
FREEBSD_DTS=${FREEBSD_DTS:-${BOARD_DIR}/dts/rk3588-g98-freebsd.dts}
FREEBSD_DTB_ESP_PATH=${FREEBSD_DTB_ESP_PATH:-/dtb/freebsd.dtb}

ROOT_LABEL=${ROOT_LABEL:-g98_root}
ZFS_POOL_NAME=${ZFS_POOL_NAME:-g98}
IMAGE_HOSTNAME=${IMAGE_HOSTNAME:-g98-rk3588}

PORT_ORIGINS=${PORT_ORIGINS:-"ports-mgmt/pkg net/realtek-rge-kmod net/motorcomm-yt921x-kmod sysutils/rk3588-installer sysutils/rk3588-uboot-config"}
