FREEBSD_KERNCONF=${FREEBSD_KERNCONF:-RK3588-NORE}

UBOOT_DEFCONFIG=${UBOOT_DEFCONFIG:-nanopc-t6-rk3588_defconfig}
UBOOT_LOGO_CONFIG=${UBOOT_LOGO_CONFIG:-RK3588_FREEBSD_SHOW_LOGO}
UBOOT_BINARY_MARKER=${UBOOT_BINARY_MARKER:-NanoPC-T6-LTS-${UBOOT_VERSION}}
UBOOT_LOGO_BMP=${UBOOT_LOGO_BMP:-${BOARD_DIR}/assets/logo.bmp}
FREEBSD_DTS=${FREEBSD_DTS:-${BOARD_DIR}/dts/rk3588-nanopc-t6-lts-freebsd.dts}
FREEBSD_DTB_ESP_PATH=${FREEBSD_DTB_ESP_PATH:-/dtb/freebsd.dtb}

ROOT_LABEL=${ROOT_LABEL:-nanopc_t6_root}
ZFS_POOL_NAME=${ZFS_POOL_NAME:-nanopc_t6}
IMAGE_HOSTNAME=${IMAGE_HOSTNAME:-nanopc-t6}
