FREEBSD_BRANCH=${FREEBSD_BRANCH:-yuri/14.3-p16_rk3588-overlay}
UBOOT_BRANCH=${UBOOT_BRANCH:-yuri/nanopc-t6_lts}
IF_RGE_BRANCH=${IF_RGE_BRANCH:-yuri/14.3}
RKBIN_BRANCH=${RKBIN_BRANCH:-master}

KERNEL_DTB=${KERNEL_DTB:-${BOARD_DIR}/dtb/rk3588-nanopi6-rev07.dtb}
MENU_CMD=${MENU_CMD:-${BOARD_DIR}/menu/freebsd14-r26-bootmenu3s.cmd}
IMAGE_DTB=${IMAGE_DTB:-${BOARD_DIR}/dtb/rk3588-nanopc-t6.dtb}
UBOOT_FDT_OVERLAYS=${UBOOT_FDT_OVERLAYS:-rk3588-nanopc-t6-typec-fixed-host.dtbo}
